package com.revature.buyNlarge.utils;

import com.revature.buyNlarge.models.*;
import com.revature.buyNlarge.services.ShipClassService;
import com.revature.buyNlarge.services.ShipService;
import com.revature.buyNlarge.services.ShipyardService;

import java.math.BigDecimal;
import java.util.*;

public class ShipFactory {
    private static final List<Shipyard> shipyards = ShipyardService.getAllShipyards();
    private static final List<ShipClass> shipClasses = ShipClassService.getAllShipClasses();
    public static void createRandomShip(){
        Random r = new Random();
        ShipService.registerShip(
                new Ship(
                        UUID.randomUUID().toString(),
                        "USS Mundanity " + r.nextInt(1000),
                        "Random Ship Generated by the Test Factory.",
                        shipyards.get(r.nextInt(shipyards.size())),
                        BigDecimal.valueOf((Math.random() * 1000000) + 1),
                        Arrays.asList(Condition.values()).get(r.nextInt(Condition.COUNT.ordinal() - 1) + 1),
                        shipClasses.get(r.nextInt(shipClasses.size())),
                        null,
                        new ArrayList<Component>()
                )
        );
    }
}
